import type { TourStep } from '../components/Tour';

export const TOUR_STEPS: TourStep[] = [
  {
    target: 'body',
    title: 'Welcome to Pulse',
    body: 'This is a short, interactive tour. Each step asks you to do something small in the UI. Pulse will move to the next step automatically when you do it. You can skip any step or the whole tour.',
    placement: 'center',
  },
  {
    target: '[data-tour="data-source"]',
    title: 'Know what data you\'re looking at',
    body: 'Every screen in Pulse is powered by the CSV shown here. You can preview it, replace it with your own, or both.',
    task: 'Click "view" to preview the current dataset.',
    placement: 'bottom',
    isComplete: (s) => s.dataPreviewOpened,
  },
  {
    target: '[data-tour="thresholds"]',
    title: 'Set the bar for "high usage"',
    body: 'The defaults are 30% usage / 20% close rate. Based on industry averages we\'ve seen, a more realistic bar is 20% usage and 40% close rate. That puts more accounts into the "stuck" and "sleeping champion" groups where the AI tool is doing the work but humans aren\'t — or vice versa.',
    task: 'Drag "High usage starts at" down to roughly 20%.',
    placement: 'right',
    isComplete: (s) => Math.abs(s.thresholdUA - 20) <= 2,
  },
  {
    target: '[data-tour="thresholds"]',
    title: 'Tighten the close rate',
    body: 'Now raise the bar for what counts as a strong close rate. 40% is a high standard — only the actual reference accounts in your portfolio will clear it.',
    task: 'Drag "Strong close rate starts at" up to roughly 40%.',
    placement: 'right',
    isComplete: (s) => Math.abs(s.thresholdCR - 40) <= 2,
  },
  {
    target: '[data-tour="scatter"]',
    title: 'Find an account to work on',
    body: 'Every dot is one account. Red = churn risk, amber = stuck (technical issue), purple = sleeping champion, green = reference. Hover for the property name; click to open it in Outreach.',
    task: 'Click any dot on the chart.',
    placement: 'left',
    isComplete: (s) => s.selectedId !== null,
  },
  {
    target: '[data-tour="section-outreach"]',
    title: 'Generate the first draft',
    body: 'When you select an account, Pulse loads its AI diagnosis, playbook, and a streaming AI-drafted email. The diagnosis runs once and is cached. The email respects the playbook for whichever health group the account sits in.',
    task: 'Click "Generate draft" (or "Regenerate" if a draft already exists).',
    placement: 'top',
    isComplete: (s) => s.hasDraftForSelected,
  },
  {
    target: '[data-tour="section-outreach"]',
    title: 'Hand it off to the right person',
    body: 'Real customer success works because the right person is on the right account. Use "Hand off…" to pick a reason (technical, training, save call, expansion, capacity), then a teammate. The next AI draft is automatically tuned for that reason — for example, a "technical issue" handoff produces an INTERNAL ticket to solutions engineering instead of a client email.',
    task: 'Click "Hand off…", pick a reason, then pick a new owner.',
    placement: 'top',
    isComplete: (s) => s.hasHandoffForSelected,
  },
  {
    target: '[data-tour="section-outreach"]',
    title: 'Send and watch a reply come back',
    body: 'In production, "Send" would POST the draft to your CRM or mail-integration webhook. In this demo it triggers the AI reply simulation: ~2 seconds later, a plausible client response streams back with a tone (positive / neutral / negative). The tone is weighted by the account\'s health group — churn risks reply colder, references reply warmer.',
    task: 'Click "Send (simulated)" on the draft and wait for the reply.',
    placement: 'top',
    isComplete: (s) => s.hasReplyForSelected,
  },
  {
    target: '[data-tour="section-team"]',
    title: 'See who\'s on the hook',
    body: 'The team section is collapsed by default. Expand it to see live workload per teammate (split by health group), plus a mini activity feed of what each person has touched.',
    task: 'Click "Show" on the Team section.',
    placement: 'top',
    isComplete: (s) => s.teamSectionOpen,
  },
  {
    target: 'body',
    title: 'You\'re set',
    body: 'That\'s the full loop. Everything you do — drafts, replies, handoffs, notes, status changes — is persisted in your browser. Refresh and it\'s all still there. Replay this tour any time from Guide → "Start tour".',
    placement: 'center',
  },
];
